### ISSUE TITLE
inclusion in f-droid repository

### ISSUE THREAD

**Issue by aetherfaerber** [farmerbb/SecondScreen#43]
Hi,

thanks for making SecondScreen and releasing its source code under a free license!

I've set up a request for packaging [over at the F-Droid issuetracker](https://gitlab.com/fdroid/rfp/issues/427) to have SecondScreen included in this repository of floss software for android.

I hope you don't mind the distribution/repackaging via f-droid or would even support it?

**Comment by farmerbb** [comment]
Sorry for the delay.  I left a comment on their issue tracker authorizing its inclusion.

**Comment by aetherfaerber** [comment]
Awesome! Thank you.
