### ISSUE TITLE
Not clear instructions how to grant permission

### ISSUE THREAD

**Issue by montvid** [farmerbb/SecondScreen#44]
In the app the information box is not clear how to give permissions via adb and the line is incorrect as it does not have a space between "free" and "android":
"pm grant com.farmerbb.secondscreen.freeandroid.permission.WRITE_SECURE_SETTINGS"
should be:
"pm grant com.farmerbb.secondscreen.free android.permission.WRITE_SECURE_SETTINGS"

The instructions should be:
Enable Developer settings -> USB debugging on your device and enter in your PC terminal
```
sudo adb start-server
sudo adb shell pm grant com.farmerbb.secondscreen.free android.permission.WRITE_SECURE_SETTINGS
```
Thanks for the great app!

**Comment by farmerbb** [comment]
I agree, the adb shell instructions aren't as clear as they should be.  I'll get this fixed in the next release.

**Comment by farmerbb** [comment]
Latest beta release on Google Play has improved instructions on how to grant the permission.

**Comment by ivanaugustobd** [comment]
> ```
> sudo adb start-server
> sudo adb shell pm grant com.farmerbb.secondscreen.free android.permission.WRITE_SECURE_SETTINGS```

`sudo` is not needed in this context

**Comment by drefcot17th** [comment]
> - [ ] K[]()

**Comment by drefcot17th** [comment]
K

**Comment by drefcot17th** [comment]
- [ ] K[]()

**Comment by Houcine72829** [comment]
com.farmerbb.secondscreen.free

**Comment by Riqueueu126** [comment]
adb shell pm grant com.farmerbb.secondscreen.free android.permission.WRITE_SECURE_SETTINGS

**Comment by malz652** [comment]
adb shell pm grant com.farmerbb.secondscreen.free android.permission.WRITE_SECURE_SETTINGS

CONTINUE

**Comment by malz652** [comment]
adb shell pm grant com.farmerbb.secondscreen.free android.permission.WRITE_SECURE_SETTINGS

**Comment by thonymontana990-creator** [comment]
Jjjiik

**Comment by shirlenejanuario4-spec** [comment]
shell pm grant com.farmerbb.secondscreen.free android.permission.WRITE_SECURE_SETTINGS

**Comment by kauanvictorpq-cyber** [comment]
sudo adb start-server
sudo adb shell pm grant com.farmerbb.secondscreen.free android.permission.WRITE_SECURE_SETTINGS

**Comment by lari89743-oss** [comment]
J
