### ISSUE TITLE
bug found in SecondScreen app ( in action button function is not working properly ) 

### ISSUE THREAD

**Issue by nasirshah1813** [farmerbb/SecondScreen#47]
#### Project Information

* Repository: https://github.com/farmerbb/SecondScreen

* Project Name: SecondScreen  

* Publisher   : Braden Farmer

#### Expected behavior
according to my knowledge when  after open the application and when i chose the function in action tab the function should be work properly and smoothly 

#### Actual behavior
after open the application when i click on the Acton button  and when i chose the some function in action tab the function is not working properly  you can see in bug video properly 

#### How to reproduce
* [download ](https://play.google.com/store/apps/details?id=com.farmerbb.secondscreen.free)and open the application 
* click on aaction button
* choose some function in action tab
* select your function   
* note the bug 
* Browser: SecondScreen version 2.7
* Operating system: android version 6.0.1
 

#### Recording Of The Bug
https://youtu.be/Ol2FtKTQALM
#### Proof of Work Done   
https://github.com/nasirshah1813

**Comment by farmerbb** [comment]
Can you go into your superuser app and verify that SecondScreen has been granted root access?
