### ISSUE TITLE
App crashes when I put the overscan values and click on ok botton.

### ISSUE THREAD

**Issue by pzdawood** [farmerbb/SecondScreen#48]
### Actual behaviour
When I open secondscreen app and click on add option . After that I put profile name and click on ok botton.then I click on overscan settings option. After that I enable overscan option . Then I put the values in  any blank and click on ok botton app suddenly crashes.
### How to reproduce
* Download the secondscreen app from F-driod.
* Install this app.
* Open the secondscreen app.
* Click on add option.
* Put profile name and Click on ok botton.
* After that select overscan settings and enable overscan.
* Fill any blank and Click on ok botton app suddenly crashes.
* Browser: secondscreen.
* Version: 2.7
* Operating system: 7.1.2
### Recording of the bug
https://youtu.be/ZM8nh-b4SUc

**Comment by farmerbb** [comment]
Thanks for your report.  I was able to reproduce the issue and commit a fix that will go out in the next release.
