### ISSUE TITLE
Logo proposal

### ISSUE THREAD

**Issue by mayowadavid** [farmerbb/SecondScreen#49]
Hello, @farmerbb i am a graphics designer. I will like to know if you want me to create a new logo for your project. I will be creating the logo for free.

**Comment by farmerbb** [comment]
Thank you very much!  I would love for you to contribute a new logo to the project :)

**Comment by mayowadavid** [comment]
I will work on it as soon as possible

**Comment by mayowadavid** [comment]
Hello @farmerbb this is what i came up with after making several sketch. You can make suggestion, so that can edit any part you want to remove before i proceed to make them into different icon sizes.
![presentation-second-screen-1](https://user-images.githubusercontent.com/34623610/42065135-33e0c6de-7b31-11e8-979e-2f81a7ec11f9.png)

**Comment by farmerbb** [comment]
Thank you so much!  I like 4, 5, and 6 more than I like 1, 2, and 3.

I do have a couple of suggestions:

* Can I see a version with #A3C638 as the background color?  (this is the app's primary color)
* Can I see a version without the phone in the foreground, just the computer monitor?

**Comment by farmerbb** [comment]
Thank you so much! I like 4, 5, and 6 more than I like 1, 2, and 3.

I do have a couple of suggestions:

* Can I see a version with #A3C638 as the background color? (this is the app's primary color)
* Can I see a version without the phone in the foreground, just the computer monitor?
* Also, a version with the phone a little bit smaller?

I really, really appreciate it!

**Comment by mayowadavid** [comment]
![requwar](https://user-images.githubusercontent.com/34623610/42132569-5f55c570-7d12-11e8-8cb9-908f3a49e292.png)
This is a preview of your request @farmerbb 
I applied a slight dark color to the screen to make it more visible, for those with color blindness.

**Comment by mayowadavid** [comment]
Hi @farmerbb which of it is your preferred choice, so that i can proceed to make other sizes.

**Comment by mayowadavid** [comment]
It is not too much, based on your suggestion. I have not create the icon yet. I was only showing you the background. Material design drop shadow will be done when i create the icon, i will get that done now.

**Comment by mayowadavid** [comment]
@farmerbb This is a launcher icon preview based on material design
xxxhdpi preview
![second screen](https://user-images.githubusercontent.com/34623610/42251042-dd873dae-7f2c-11e8-8b56-6b0faa461c42.png)
xxhdpi preview
![second screen-1](https://user-images.githubusercontent.com/34623610/42251049-e9598a1a-7f2c-11e8-9616-0ad49acc7df1.png)
If you like it i will proceed to make a pull request, why i also submit a link to editable files.

**Comment by farmerbb** [comment]
Looks fantastic! Thank you so much!

**Comment by mayowadavid** [comment]
Am glad you like it i will go and make a pull request. This is a link to editable file[here]( https://drive.google.com/file/d/1Vd9etfNwS88GX5UQPlslXSNtei7ADW4i/view?usp=sharing), i use android studio to create drop down shadow for material design.

**Comment by mayowadavid** [comment]
@farmerbb i have create a pull request i have replaced old icon with new icon

**Comment by farmerbb** [comment]
Thank you very, very much!  

I went ahead and merged your pull request, but I am going to make a few small tweaks myself using the PDF you linked (mainly to support adaptive icons on Android 8.0+)

I'll make sure to attribute you with "App logo by mayowadavid" on the about screen :)

**Comment by mayowadavid** [comment]
Hello @farmerbb there is no need to make any tweak i just include a file with an adaptive icon.

**Comment by mayowadavid** [comment]
@farmerbb in case you need any other thing about the logo am always  available.
