### ISSUE TITLE
Use Miracast Presentation Mode to extend the android phone display

### ISSUE THREAD

**Issue by Maccer1** [farmerbb/SecondScreen#60]
[Here](http://www.ijitr.com/index.php/ojs/article/viewFile/555/pdf) is a paper that says it's possible to do. It would be great if your app could do it, that way I could watch a video on the TV screen while using my phone normally (like you can do with the YouTube app).

**Comment by farmerbb** [comment]
Thanks for your suggestion.  SecondScreen doesn't provide the ability to mirror the screen to a secondary display itself, rather, it enhances your device's existing screen mirroring solutions for an overall better experience.  Miracast is something that would have to be implemented by the OEM of your device.
